// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyYCb9CzX_gxufiUv6eMQjQQEZISequM8',
    appId: '1:145461889640:web:01ca5fda1f598a421109dd',
    messagingSenderId: '145461889640',
    projectId: 'evently-c17-f0fd9',
    authDomain: 'evently-c17-f0fd9.firebaseapp.com',
    storageBucket: 'evently-c17-f0fd9.firebasestorage.app',
    measurementId: 'G-WPWYR0GED2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUBZ72I8KtBaS2Y0Bn1qB7TzIbafRV2hA',
    appId: '1:145461889640:android:628d6e80f0d206311109dd',
    messagingSenderId: '145461889640',
    projectId: 'evently-c17-f0fd9',
    storageBucket: 'evently-c17-f0fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYM_4FvNKKlKyvr-nzIAHivHPzmcmJQM',
    appId: '1:145461889640:ios:07e2142b1795f4da1109dd',
    messagingSenderId: '145461889640',
    projectId: 'evently-c17-f0fd9',
    storageBucket: 'evently-c17-f0fd9.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoYM_4FvNKKlKyvr-nzIAHivHPzmcmJQM',
    appId: '1:145461889640:ios:07e2142b1795f4da1109dd',
    messagingSenderId: '145461889640',
    projectId: 'evently-c17-f0fd9',
    storageBucket: 'evently-c17-f0fd9.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyYCb9CzX_gxufiUv6eMQjQQEZISequM8',
    appId: '1:145461889640:web:2835b2476ef94ff21109dd',
    messagingSenderId: '145461889640',
    projectId: 'evently-c17-f0fd9',
    authDomain: 'evently-c17-f0fd9.firebaseapp.com',
    storageBucket: 'evently-c17-f0fd9.firebasestorage.app',
    measurementId: 'G-YR6TJVCR0K',
  );
}
